version: '2'

services:

  webshark:
    #image: ghcr.io/qxip/webshark:2.0.0
    build: .
    container_name: webshark
    expose:
      - "8085"
    ports:
      - "8086:8085"
    volumes:
      - ./captures:/captures
    environment:
      - SHARKD_SOCKET=/home/node/sharkd.sock
      - CAPTURES_PATH=/captures/
